services:
  database:
    image: postgres:17.4
    working_dir: /database
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - databaseVolume:/var/lib/postgresql/data
      - ./init_scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  backend:
    image: backend:latest
    build: ./backend
    working_dir: /backend
    environment:
      DB_URL:
      DB_USER:
      DB_PASSWORD: ${DATABASE_PASSWORD}
    ports: 
      - "8080:8080"
    depends_on:
      - database

volumes:
  databaseVolume: