services:
  database:
    image: postgres:17.4
    working_dir: /database
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - databaseVolume:/var/lib/postgresql/data
      - ./init_scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  frontend:
    image: social-app-fronted:latest
    build: ./frontend
    working_dir: /frontend
    ports:
      - "3000:80"

  backend:
    image: social-app-backend:latest
    build: ./backend
    working_dir: /backend
    environment:
      DB_URL: ${DATABASE_URL}
      DB_USER: ${DATABASE_USER}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      KEYSTORE_PASSWORD: ${KEYSTORE_PASSWORD}
      JWT_REFRESH: ${JWT_REFRESH}
      JWT_ACCESS: ${JWT_ACCESS}
    volumes:
      - social-app-keys:/keystore
    ports: 
      - "8080:8080"
    depends_on:
      - database

volumes:
  databaseVolume:
  social-app-keys: